
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://openawg.github.io"
https-host: "openawg.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

#baseurl: /personal-jekyll-theme

# Google tracking id to track your visitors

google-tracking-id: "UA-72887853-1"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "OpenAWG"
title: "[ OpenAWG ]"
description: "Open source water generation"
# keywords: "smith, jones, personal, jekyll, theme"
favicon: "/img/favicon.ico"
# 404-img: "/img/labtocat.png"

################
# Header layout #
################

black-favicon: "/img/black-lab-glass.ico"

# background-img: "../img/pexels-photo-37487.jpeg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: False
# shuffle: True # Shuffle the lines.
# loop: True
# loop-count: False # Set False for infinite loop, or set any number for finite loop.
# type-speed: 10
# start-delay: 200
# delete-delay: 5000
# lines: # You can add HTML Tags in the Text
#   - text: "The lower you fall, the higher you'll fly."
#   - text: "Where’s your will to be weird?"
# 
# me-img: "/img/jetpacktocat.png"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True

disqus-shortname: "openawg"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: ""
    date: "Now"
    description: "Work is currently ongoing for models, prototypes, budgets, fundraisers, etc."
  - image: ""
    date: "February 2016"
    description: "BlueIce Alpha is open sourced"
  - image: ""
    date: "February 2016"
    description: "Submitted BRC Honoraria Application"
  - image: "/assets/IMG_9957.jpg"
    date: "January 2016"
    description: "For the next prototype, we needed to scale the POC to produce a larger amount of water. By taking a heat pump already optimized for the task of phase changing water vapor, we reduced the amount of work needed to get an MVP up and running, and slapped a pump onto a reverse osmosis filtration system."
  - image: ""
    date: "December 2015"
    description: "Invited to submit BRC Honoraria Application"
  - image: ""
    date: "December 2015"
    description: "With Ted’s climate prediction, we were able to run some calculations and produce a rough model describing what will happen given a bunch of independent variables like heat pumping capacity, energy consumption of components, etc. We are currently using [heat pump model here] and predict a capacity of 65L / 24h with an efficiency of 637 Wh/L. Given that specific heat consumes some of the heat pumping capacity, we can separate our concerns by utilizing a separate heat pump for lowering the temperature of the incoming air (pretreatment)."
  - image: ""
    date: "November 2015"
    description: "Submitted BRC Honoraria LOI"
  - image: ""
    date: "November 2015"
    description: "In our search for BRD (Black Rock Desert) weather data, we found some weather stations nearby (~20 miles: DRYN2 @ [41.50000, -119.11670]), but the terrain might cause microclimates. We asked around, and got introduced to Ted Hullar, a meteorologist who has run a weather station at Burning Man for the past couple of years. Ted was able to calculate a climate prediction normalized against the surrounding weather stations in the area and provide hourly averages (high, average, low) for late August and early September."
  - image: "/assets/IMG_9364.jpg"
    date: "September 2015"
    description: "A quick and easy POC (proof of concept) thrown together with spare parts. I was reading about the water crisis and realized I had some TECs (thermoelectric coolers) and small radiators laying around, so I tried pumping some heat around."

# First image of the Timeline

timeline-img: "/img/timeline/default.png"

###########
# Contact #
###########

#email: "your@email.here"

##################
# Social Buttons #
##################

social:
#  - title: "facebook"
#    url: "https://facebook.com/"
#  - title: "twitter"
#    url: "https://twitter.com/"
  - title: "github"
    url: "https://github.com/openawg/openawg"
#  - title: "bitcoin"
#    url: "https://blockchain.info/address/1LHuKC9Em3KA5yoZaf7nngnNdf9K7s2gSi"
#  - title: "rss"
#    url: "/feed.xml"

############
# 404 page #
############

# 404-img: "/img/labtocat.png"

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Blog: 'latest-post'
  Timeline: 'timeline'
#   Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
